# Generated by Django 6.0.1 on 2026-03-18 11:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0003_alter_listingimage_uploaded_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('service_use', 'Service Use')], max_length=15)),
                ('agreed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('cash_on_pickup', 'Cash on Pickup'), ('pay_after_service', 'Pay After Service')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('auto_completed', 'Auto Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('auto_complete_date', models.DateField(blank=True, null=True)),
                ('inquiry_note', models.TextField(blank=True)),
                ('mpesa_phone', models.CharField(blank=True, max_length=20)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='listings.listing')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['buyer'], name='transaction_buyer_i_c1bfcb_idx'), models.Index(fields=['seller'], name='transaction_seller__b9c73a_idx'), models.Index(fields=['status'], name='transaction_status_71abbb_idx'), models.Index(fields=['listing'], name='transaction_listing_674802_idx')],
            },
        ),
    ]
