# Generated by Django 6.0.1 on 2026-04-15 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_notification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='transaction_recipie_97aea4_idx',
            old_name='transactio_recipie_6fba7b_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='transaction_created_eec4c2_idx',
            old_name='transactio_created_6f3359_idx',
        ),
    ]
