# Generated by Django 6.0.1 on 2026-05-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='buyer_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='confirmation_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='disputed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('purchase_created', 'Purchase Created'), ('receipt_ready', 'Receipt Ready'), ('delivery_marked', 'Delivery Marked'), ('receipt_confirmed', 'Receipt Confirmed'), ('delivery_disputed', 'Delivery Disputed')], max_length=32),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('auto_completed', 'Auto Completed'), ('pending_confirmation', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
