# Generated by Django 6.0.1 on 2026-05-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_add_confirmation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_disputed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('auto_completed', 'Auto Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
