# Generated by Django 6.0.1 on 2026-05-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_notification_generic'),
        ('transactions', '0007_simplify_status_add_seller_flags'),
    ]

    operations = [
    ]
