# Generated by Django 6.0.1 on 2026-05-04 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('transactions', '0007_simplify_status_add_seller_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='transactions.transaction'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('fake_misleading', 'Fake or misleading listing'), ('prohibited_item', 'Prohibited item'), ('suspected_scam', 'Suspected scam'), ('inappropriate_content', 'Inappropriate content'), ('delivery_dispute', 'Delivery dispute'), ('other', 'Other')], max_length=30),
        ),
    ]
