# Generated by Django 6.0.1 on 2026-01-22 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Books', 'Books'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Furniture', 'Furniture'), ('Services', 'Services'), ('Food & Beverages', 'Food & Beverages'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('negotiable', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('condition', models.CharField(blank=True, choices=[('New', 'New'), ('Like New', 'Like New'), ('Used', 'Used'), ('Fair', 'Fair')], max_length=20)),
                ('area_of_operation', models.CharField(max_length=255)),
                ('contact_preference', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('is_draft', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
        ),
    ]
