# Generated by Django 6.0.1 on 2026-03-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_options_alter_listingimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
