# Generated by Django 6.0.1 on 2026-05-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_min_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('books', 'Academics'), ('electronics', 'Electronics'), ('fashion', 'Fashion'), ('furniture', 'Furniture'), ('food_beverages', 'Food & Beverages'), ('beauty', 'Beauty'), ('stationery', 'Stationery & Supplies'), ('sports', 'Sports & Fitness'), ('tutoring', 'Tutoring & Academics'), ('printing', 'Printing & Photocopying'), ('design', 'Design & Creative'), ('tech_repair', 'Tech & Repairs'), ('laundry', 'Laundry & Cleaning'), ('photography', 'Photography & Video'), ('other', 'Other')], max_length=20),
        ),
    ]
