# Generated by Django 6.0.1 on 2026-05-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='listingquestion',
            new_name='questions_l_listing_30082b_idx',
            old_name='questions_l_listing_idx',
        ),
    ]
