# Generated by Django 6.0.1 on 2026-05-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_split_full_name'),
        ('accounts', '0007_user_profile_picture'),
    ]

    operations = [
    ]
