# Generated by Django 6.0.1 on 2026-03-18 11:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.UUIDField(blank=True, help_text='ID of the transaction that generated this review.', null=True)),
                ('listing_title', models.CharField(blank=True, help_text='Snapshot of the listing title at time of review.', max_length=255)),
                ('score', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5 stars.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reviewee'], name='reviews_rev_reviewe_57bac6_idx'), models.Index(fields=['reviewer'], name='reviews_rev_reviewe_e817a5_idx'), models.Index(fields=['transaction_id'], name='reviews_rev_transac_f05f5f_idx')],
                'unique_together': {('reviewer', 'transaction_id')},
            },
        ),
    ]
