# Generated by Django 6.0.1 on 2026-04-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_rename_transactio_recipie_6fba7b_idx_transaction_recipie_97aea4_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('purchase_created', 'Purchase Created'), ('receipt_ready', 'Receipt Ready')], max_length=32),
        ),
    ]
