# Generated by Django 6.0.1 on 2026-05-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_transaction_dispute_deadline_escalated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('purchase_created', 'Purchase Created'), ('receipt_ready', 'Receipt Ready'), ('delivery_marked', 'Delivery Marked'), ('receipt_confirmed', 'Receipt Confirmed'), ('delivery_disputed', 'Delivery Disputed'), ('seller_verified', 'Seller Verified'), ('seller_revoked', 'Seller Status Revoked'), ('account_suspended', 'Account Suspended'), ('account_reactivated', 'Account Reactivated'), ('review_received', 'Review Received'), ('report_acted', 'Report Acted On'), ('report_dismissed', 'Report Dismissed'), ('listing_archived', 'Listing Archived'), ('dispute_resolved', 'Dispute Resolved')], max_length=32),
        ),
    ]
