# Generated by Django 6.0.1 on 2026-05-15 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_alter_notification_notification_type'),
        ('transactions', '0010_transaction_mpesa_paid'),
    ]

    operations = [
    ]
