# Generated by Django 6.0.1 on 2026-05-15 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_notification_listing_field'),
        ('transactions', '0011_merge_20260515_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('purchase_created', 'Purchase Created'), ('receipt_ready', 'Receipt Ready'), ('delivery_marked', 'Delivery Marked'), ('receipt_confirmed', 'Receipt Confirmed'), ('delivery_disputed', 'Delivery Disputed'), ('seller_verified', 'Seller Verified'), ('seller_revoked', 'Seller Status Revoked'), ('account_suspended', 'Account Suspended'), ('account_reactivated', 'Account Reactivated'), ('review_received', 'Review Received'), ('report_acted', 'Report Acted On'), ('report_dismissed', 'Report Dismissed'), ('listing_archived', 'Listing Archived'), ('dispute_resolved', 'Dispute Resolved'), ('question_asked', 'Question Asked'), ('question_answered', 'Question Answered')], max_length=32),
        ),
    ]
