# Generated by Django 6.0.1 on 2026-05-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_add_transaction_and_delivery_dispute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_mediation', 'Parties Asked to Resolve'), ('dismissed', 'Dismissed'), ('acted', 'Acted On')], default='pending', max_length=15),
        ),
    ]
