# Generated by Django 6.0.1 on 2026-04-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listingimage_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='min_discount_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
