import { fetchLogoBase64, drawLogo } from '../../utils/pdfLogo';

export const EMERALD = [5, 150, 105];
export const WHITE   = [255, 255, 255];

export const fmtDate = (iso) =>
  iso ? new Date(iso).toLocaleDateString('en-KE', { day: 'numeric', month: 'short', year: 'numeric' }) : '—';

export const fmtFull = (d) =>
  d.toLocaleDateString('en-KE', { weekday: 'long', day: '2-digit', month: 'long', year: 'numeric' }) +
  ' at ' + d.toLocaleTimeString('en-KE', { hour: '2-digit', minute: '2-digit', hour12: true });

export async function buildBase(title) {
  const { jsPDF } = await import('jspdf');
  const { default: autoTable } = await import('jspdf-autotable');
  const now = new Date();
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const W = doc.internal.pageSize.getWidth();

  const logoBase64 = await fetchLogoBase64();

  doc.setFillColor(...EMERALD); doc.rect(0, 0, W, 30, 'F');
  const textX = drawLogo(doc, logoBase64, 30);
  doc.setFont('helvetica', 'bold');   doc.setFontSize(16); doc.setTextColor(...WHITE); doc.text('KUuza', textX, 16);
  doc.setFont('helvetica', 'normal'); doc.setFontSize(7);  doc.setTextColor(200, 245, 230);
  doc.text('Kenyatta University Official Marketplace', textX, 23);
  doc.setFont('helvetica', 'bold');   doc.setFontSize(13); doc.setTextColor(...WHITE);
  doc.text(title, W - 14, 10, { align: 'right' });
  doc.setFont('helvetica', 'normal'); doc.setFontSize(7);  doc.setTextColor(200, 245, 230);
  doc.text('GENERATED BY', W - 14, 16, { align: 'right' });
  doc.setFont('helvetica', 'bold');   doc.setFontSize(11); doc.setTextColor(...WHITE);
  doc.text('KUuza Admin', W - 14, 22, { align: 'right' });
  doc.setFont('helvetica', 'normal'); doc.setFontSize(7);  doc.setTextColor(200, 245, 230);
  doc.text(`Issued on: ${fmtFull(now)}`, W - 14, 28, { align: 'right' });
  doc.setDrawColor(16, 185, 129); doc.setLineWidth(0.3); doc.line(0, 30, W, 30);

  return { doc, autoTable, W, Y: 36 };
}

export function statBoxes(doc, Y, W, heading, boxes) {
  const uw = W - 28, gap = 5;
  const bw = (uw - gap * (boxes.length - 1)) / boxes.length;
  const bh = 20, bg = bh + 18;
  doc.setFillColor(240, 253, 250); doc.roundedRect(14, Y, uw, bg, 2, 2, 'F');
  doc.setFont('helvetica', 'bold'); doc.setFontSize(8); doc.setTextColor(...EMERALD);
  doc.text(heading, 18, Y + 6);
  const top = Y + 9;
  boxes.forEach((b, i) => {
    const bx = 14 + i * (bw + gap);
    doc.setFillColor(255, 255, 255); doc.roundedRect(bx, top, bw, bh, 1.5, 1.5, 'F');
    doc.setFont('helvetica', 'normal'); doc.setFontSize(6.5); doc.setTextColor(107, 114, 128);
    doc.text(b.label.toUpperCase(), bx + 4, top + 6);
    doc.setFont('helvetica', 'bold'); doc.setFontSize(12); doc.setTextColor(...EMERALD);
    doc.text(String(b.value), bx + 4, top + 15);
  });
  return Y + bg;
}

export function footers(doc, W) {
  const n = doc.internal.getNumberOfPages();
  for (let p = 1; p <= n; p++) {
    doc.setPage(p);
    const fy = doc.internal.pageSize.height - 7;
    doc.setDrawColor(210, 210, 210); doc.setLineWidth(0.2);
    doc.line(14, fy - 2.5, W - 14, fy - 2.5);
    doc.setFontSize(6.5); doc.setTextColor(150, 150, 150);
    doc.text('KUuza · Kenyatta University Official Marketplace · hello.kuuza@gmail.com', 14, fy);
    doc.text(`Page ${p} of ${n}`, W - 14, fy, { align: 'right' });
  }
}