# Generated by Django 6.0.1 on 2026-05-15 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0005_notification_listing_field'),
        ('transactions', '0013_remove_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('purchase_created', 'Purchase Created'), ('receipt_ready', 'Receipt Ready'), ('delivery_marked', 'Delivery Marked'), ('receipt_confirmed', 'Receipt Confirmed'), ('delivery_disputed', 'Delivery Disputed'), ('seller_verified', 'Seller Verified'), ('seller_revoked', 'Seller Status Revoked'), ('account_suspended', 'Account Suspended'), ('account_reactivated', 'Account Reactivated'), ('review_received', 'Review Received'), ('report_acted', 'Report Acted On'), ('report_dismissed', 'Report Dismissed'), ('listing_archived', 'Listing Archived'), ('dispute_resolved', 'Dispute Resolved'), ('question_asked', 'Question Asked'), ('question_answered', 'Question Answered')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_notifications', to='listings.listing')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tx_notifications', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
